### ISSUE TITLE
Add `@TEST-PORT-RANGE`

### ISSUE THREAD

**Issue by J-Gras** [zeek/btest#102]
Having something like `@TEST-PORT-RANGE <env> <num>` to get a range of `<num>` ports would be handy.

**Comment by bbannier** [comment]
Do you want this to bulk reserve a number of ports, or because you need a consecutive range of ports (why?)?

For bulk reservation I am not sure this would be that useful.

One can already "reserve"[^1] multiple ports in a test, see e.g., https://github.com/zeek/zeek/blob/master/testing/btest/scripts/policy/frameworks/telemetry/prometheus.zeek#L6-L11. For the existing `@TEST-PORT MY_PORT` the "reserved" port value can then be accessed from the test via the env var `MY_PORT` so one can directly correlate reserving of a port and its use.

For a `@TEST-PORT-RANGE` I could imagine accessing them via constructed env var names, e.g.,

```
@TEST-PORT-RANGE MY_PORTS 3
```
could yield env vars

```
MY_PORTS1
MY_PORTS2
MY_PORTS3
```

Getting from use to reservation would require some mental work. Additionally, for this case reserving the ports manually would only be slightly longer than 

[^1]: This is already only best effort since the port is only assigned inside BTest's bookkeeping. Nothing guarantees that a `bind` on that port later in the test would be useful (e.g., the port might already be used by another process on the system).

**Comment by bbannier** [comment]
Closing this as it is unclear how to expose such functionality. I am personally also not a fan of this providing functionality to automatically "reserve" wide ranges of ports makes it more likely to run into issues where the OS hands out port in the ephemeral range without BTest being aware.
